apiVersion: v1
kind: Service
metadata:
    name: "myownk8-8881"
    labels:
        app: "myownk8-8881"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "myownk8-8881"