apiVersion: v1
kind: Service
metadata:
    name: "k8k8k8-28ed"
    labels:
        app: "k8k8k8-28ed"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "k8k8k8-28ed"