apiVersion: v1
kind: Service
metadata:
    name: "myownacr-c95e"
    labels:
        app: "myownacr-c95e"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "myownacr-c95e"