on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: myownacr.azurecr.io
        username: ${{ secrets.acr_myownacr_username }}
        password: ${{ secrets.acr_myownacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t myownacr.azurecr.io/myownacr:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push myownacr.azurecr.io/myownacr:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_myownacr_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep myownacracad | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace myownacracad`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: myownacracad
        container-registry-url: myownacr.azurecr.io
        container-registry-username: ${{ secrets.acr_myownacr_username }}
        container-registry-password: ${{ secrets.acr_myownacr_password }}
        secret-name: myownacrdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: myownacracad
        manifests: |
          manifests/deployment-2.yml
          manifests/service-2.yml
        images: |
          myownacr.azurecr.io/myownacr:${{ github.sha }}
        imagepullsecrets: |
          myownacrdockerauth
