on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: myownacr.azurecr.io
        username: ${{ secrets.acr_myownacr_username }}
        password: ${{ secrets.acr_myownacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t myownacr.azurecr.io/aks7:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push myownacr.azurecr.io/aks7:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aks7_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aks78988 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aks78988`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aks78988
        container-registry-url: myownacr.azurecr.io
        container-registry-username: ${{ secrets.acr_myownacr_username }}
        container-registry-password: ${{ secrets.acr_myownacr_password }}
        secret-name: aks7dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aks78988
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          myownacr.azurecr.io/aks7:${{ github.sha }}
        imagepullsecrets: |
          aks7dockerauth
